import torch
import torch.nn as nn
import torch.nn.functional as F

# generated by ChatGPT

class MultiHeadAttention(nn.Module):
    def __init__(self, embed_size, num_heads):
        super(MultiHeadAttention, self).__init__()
        self.embed_size = embed_size
        self.num_heads = num_heads
        self.head_dim = embed_size // num_heads

        assert (
            self.head_dim * num_heads == embed_size
        ), "Embedding size needs to be divisible by num_heads"

        self.values = nn.Linear(self.head_dim, self.head_dim, bias=False)
        self.keys = nn.Linear(self.head_dim, self.head_dim, bias=False)
        self.queries = nn.Linear(self.head_dim, self.head_dim, bias=False)
        self.fc_out = nn.Linear(num_heads * self.head_dim, embed_size)

    def forward(self, values, keys, query, mask):
        # Get number of training examples
        N = query.shape[0]

        value_len, key_len, query_len = values.shape[1], keys.shape[1], query.shape[1]

        # Split the embedding into self.num_heads different pieces
        values = values.reshape(N, value_len, self.num_heads, self.head_dim)
        keys = keys.reshape(N, key_len, self.num_heads, self.head_dim)
        queries = query.reshape(N, query_len, self.num_heads, self.head_dim)

        values = self.values(values)
        keys = self.keys(keys)
        queries = self.queries(queries)

        energy = torch.einsum("nqhd,nkhd->nhqk", [queries, keys])

        if mask is not None:
            energy = energy.masked_fill(mask == 0, float("-1e20"))

        attention = torch.nn.functional.softmax(
            energy / (self.embed_size ** (1 / 2)), dim=3
        )

        out = torch.einsum("nhql,nlhd->nqhd", [attention, values]).reshape(
            N, query_len, self.num_heads * self.head_dim
        )

        out = self.fc_out(out)
        return out


class TransformerBlock(nn.Module):
    def __init__(self, embed_size, num_heads, ff_hidden_size, dropout):
        super(TransformerBlock, self).__init__()
        self.attention = MultiHeadAttention(embed_size, num_heads)
        self.feedforward = nn.Sequential(
            nn.Linear(embed_size, ff_hidden_size),
            nn.ReLU(),
            nn.Linear(ff_hidden_size, embed_size),
        )
        self.norm1 = nn.LayerNorm(embed_size)
        self.norm2 = nn.LayerNorm(embed_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, value, key, query, mask):
        attention = self.attention(value, key, query, mask)

        # Add skip connection and norm
        x = self.dropout(self.norm1(attention + query))
        forward = self.feedforward(x)

        # Add skip connection and norm
        out = self.dropout(self.norm2(forward + x))
        return out


class SimpleViT(nn.Module):
    def __init__(
        self,
        input_size,
        embed_size=768,
        num_heads=12,
        num_transformer_blocks=12,
        ff_hidden_size=3072,
        dropout=0.1,
    ):
        super(SimpleViT, self).__init__()
        self.embedding = nn.Linear(
            input_size, embed_size
        )  # Linear layer instead of Conv2d
        self.transformer_blocks = nn.ModuleList(
            [
                TransformerBlock(embed_size, num_heads, ff_hidden_size, dropout)
                for _ in range(num_transformer_blocks)
            ]
        )
        self.fc = nn.Linear(embed_size, 1)  # Regression output with a single value
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask):
        x = self.embedding(x)
        x = x.unsqueeze(1)  # Add a dimension for sequence length (assuming 1D input)
        for transformer in self.transformer_blocks:
            x = transformer(x, x, x, mask)
        x = x.mean(dim=1)
        x = self.fc(x)
        return x


# Example usage:
# model = VisionTransformer(input_size=40000)
# input_tensor = torch.randn((1, 40000))  # Example input array with size (40000,)
# mask = torch.ones((1, 1, 1))  # Example mask with size (1,)
# output = model(input_tensor, mask)
# print(output.shape)
