import torch
import torch.nn as nn
import torch.nn.functional as F

# generated by GPT4
# Cost to generate 0.04$ - 13LKR
# Gave the SimpleViT and asked to improve it


class MultiHeadAttention(nn.Module):
    def __init__(self, embed_size, num_heads):
        super(MultiHeadAttention, self).__init__()
        self.embed_size = embed_size
        self.num_heads = num_heads
        self.head_dim = embed_size // num_heads

        assert (
            self.head_dim * num_heads == embed_size
        ), "Embedding size needs to be divisible by num_heads"

        self.values = nn.Linear(self.head_dim, self.head_dim, bias=False)
        self.keys = nn.Linear(self.head_dim, self.head_dim, bias=False)
        self.queries = nn.Linear(self.head_dim, self.head_dim, bias=False)
        self.fc_out = nn.Linear(num_heads * self.head_dim, embed_size)

    def forward(self, values, keys, query, mask):
        # Get number of training examples
        N = query.shape[0]

        value_len, key_len, query_len = values.shape[1], keys.shape[1], query.shape[1]

        # Split the embedding into self.num_heads different pieces
        values = values.reshape(N, value_len, self.num_heads, self.head_dim)
        keys = keys.reshape(N, key_len, self.num_heads, self.head_dim)
        queries = query.reshape(N, query_len, self.num_heads, self.head_dim)

        values = self.values(values)
        keys = self.keys(keys)
        queries = self.queries(queries)

        energy = torch.einsum("nqhd,nkhd->nhqk", [queries, keys])

        if mask is not None:
            energy = energy.masked_fill(mask == 0, float("-1e20"))

        attention = torch.nn.functional.softmax(
            energy / (self.embed_size ** (1 / 2)), dim=3
        )

        out = torch.einsum("nhql,nlhd->nqhd", [attention, values]).reshape(
            N, query_len, self.num_heads * self.head_dim
        )

        out = self.fc_out(out)
        return out


class TransformerBlock(nn.Module):
    def __init__(self, embed_size, num_heads, ff_hidden_size, dropout):
        super(TransformerBlock, self).__init__()
        self.attention = MultiHeadAttention(embed_size, num_heads)
        self.feedforward = nn.Sequential(
            nn.Linear(embed_size, ff_hidden_size),
            nn.ReLU(),
            nn.Linear(ff_hidden_size, embed_size),
        )
        self.norm1 = nn.LayerNorm(embed_size)
        self.norm2 = nn.LayerNorm(embed_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, value, key, query, mask):
        attention = self.attention(value, key, query, mask)

        # Add skip connection and norm
        x = self.dropout(self.norm1(attention + query))
        forward = self.feedforward(x)

        # Add skip connection and norm
        out = self.dropout(self.norm2(forward + x))
        return out


class SimpleECGViT(nn.Module):
    def __init__(
        self,
        input_size,
        embed_size=768,
        num_heads=12,
        num_transformer_blocks=12,
        ff_hidden_size=3072,
        dropout=0.1,
        sequence_length=500,  # We're going to chunk the input into segments
    ):
        super(SimpleECGViT, self).__init__()
        self.sequence_length = sequence_length
        self.embed_size = embed_size
        self.embedding = nn.Linear(sequence_length, embed_size)
        self.positional_encodings = nn.Parameter(torch.randn(1, 1, embed_size))
        self.transformer_blocks = nn.ModuleList(
            [
                TransformerBlock(embed_size, num_heads, ff_hidden_size, dropout)
                for _ in range(num_transformer_blocks)
            ]
        )
        self.out = nn.Linear(embed_size, 1)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        # Assume x is of shape (N, input_size), where input_size is 40,000
        N = x.shape[0]

        # Break the input into sequence_length segments
        num_segments = x.shape[1] // self.sequence_length
        x = x.view(N, num_segments, self.sequence_length)

        # Embed each segment separately
        x = self.embedding(x)  # Shape: (N, num_segments, embed_size)

        # Add positional embeddings (Note: actual positional encodings might need to be more sophisticated)
        positions = torch.arange(0, num_segments).unsqueeze(1).to(x.device)
        x += self.positional_encodings[:, :num_segments, :] * positions

        # Forward through the transformer blocks
        for transformer in self.transformer_blocks:
            x = transformer(x, x, x, mask)

        # Pool the segment representations
        x = x.mean(dim=1)

        # Output layer
        x = self.dropout(x)
        x = self.out(x)
        return x
